[agentcloud]
pg1-path=/var/lib/postgresql/data
pg1-user=agentcloud
pg1-database=agentcloud

[global]
repo1-path=/var/lib/pgbackrest
repo1-cipher-type=aes-256-cbc
repo1-cipher-pass=@CIPHER_PASS@
repo1-retention-full=2
start-fast=y
archive-timeout=60
archive-async=n
log-level-console=warn
log-level-file=off
lock-path=/tmp/pgbackrest
spool-path=/var/spool/pgbackrest
process-max=1

[global:archive-push]
compress-level=3
